org: funguardian
app: expense-app
service: expense-app

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  region: ap-southeast-1
  stage: dev
  timeout: 20
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::123textract123/*"
        - Effect: Allow
          Action:
            - "textract:*"
          Resource:
            - "*"

functions:
  document-to-text:
    handler: wsgi_handler.handler
    url: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!.serverless/**"
